// Inherited class; the Ui_ugpMainWindow might be changed by
// Qt Designer, so the relevant bindings must operate here

#ifndef MICROGPENTROPICDISTANCEWINDOW
#define MICROGPENTROPICDISTANCEWINDOW

#include "ui_ugp3-entropic-distance.h"

// forward declaration
namespace ugp3
{
	namespace core
	{
		class EvolutionaryAlgorithm;
		class EnhancedIndividual;
	}
}

namespace Ui 
{

// forward declaration
class MicroGPMainWindow;

// everything in the Ui_ugpMainWindow is public
// multiple inheritance requires QObject to be first
class MicroGPEntropicDistanceWindow : public QObject, public Ui_entropicDistanceWindow
{

Q_OBJECT

private:
	// pointer to main window
	MicroGPMainWindow* mainWindow;
	
	// pointers to starting and end points
	ugp3::core::EnhancedIndividual* startingPoint;
	std::vector<ugp3::core::EnhancedIndividual*> endPoints;

public:
	// initialize window
	void setupUi(MicroGPMainWindow* parentWindow, QDialog* parentDialog);
	// compute entropic distance
	double computeEntropicDistance(ugp3::core::EnhancedIndividual* startingPoint, ugp3::core::EnhancedIndividual* endPoint);

// slots that will be connected to signals generated by objects
public slots:
	void fillSymbolsTable(int currentRow, int currentColumn, int previousRow, int previousColumn);
};

} // namespace Ui

#endif
