// Inherited class; the Ui_SelectOperators might be changed by
// Qt Designer, so the relevant bindings must operate here

#ifndef MICROGPSELECTOPERATORS
#define MICROGPSELECTOPERATORS

#include "ui_ugp3-selectOperators.h"

namespace Ui 
{

// forward declaration
class MicroGPMainWindow;

// everything in the Ui_SelectOperators is public
// multiple inheritance requires QObject to be first
class MicroGPSelectOperators : public QObject, public Ui_SelectOperators
{

Q_OBJECT

private:
	QDialog* parentDialog;
	std::map<std::string,std::string> operatorDescriptions;

public:
	// general setup
	void setupUi(MicroGPMainWindow* parentWindow, QDialog* parentDialog);

// slot that will be connected to signals generated by objects
public slots:
	// add operator
	void addOperator();
	// remove operator
	void removeOperator();

};

} // namespace Ui

#endif
